[package]
name = "qti-render"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
qti-core = { path = "../qti-core" }
serde.workspace = true
serde_json.workspace = true
scraper.workspace = true
lol_html.workspace = true
regex.workspace = true
thiserror.workspace = true
base64.workspace = true
sha2.workspace = true
png.workspace = true
