[package]
name = "qti-cli"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
time.workspace = true
clap.workspace = true
thiserror.workspace = true
qti-core = { path = "../qti-core" }
qti-engines = { path = "../qti-engines" }
qti-integrity = { path = "../qti-integrity" }

[dev-dependencies]
tempfile.workspace = true
