[package]
name = "qti-core"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true

[dependencies]
serde.workspace = true
thiserror.workspace = true
crc.workspace = true
regex.workspace = true
quick-xml.workspace = true
scraper.workspace = true
lol_html.workspace = true
sha2.workspace = true
base64.workspace = true
percent-encoding.workspace = true
indexmap.workspace = true
zip.workspace = true

[dev-dependencies]
serde_json.workspace = true
